version: '3.8'
services:
  monitor:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - DISK_THRESHOLD=${DISK_THRESHOLD}
    restart: unless-stopped 